# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: sudo docker login -u $(DOCKER_USER) -p $(DOCKER_PASSWORD)
      displayName: Login to Docker Hub
    - script: sudo docker pull homeassistant/amd64-builder
      displayName: Install hassio builder
    - script: |
        docker run --rm --privileged -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw \
        -v $(pwd)/radicale:/data:ro homeassistant/amd64-builder --all -t /data \
        --no-latest --test
      displayName: Build radicale with tag :test (no push)